### ISSUE TITLE
Degenerate rendering on some classes

### ISSUE THREAD

**Issue by kevinniechen** [konaraddi/umd-course-vis#3]
e.g if I run "CMSC412" it seems to lag a lot. it could be an issue with the js library?

**Comment by konaraddi** [comment]
Classes with long `from (....)` statements (e.g. CMSC412's prerequisites) were slow to load because GET requests were being made recursively on each course within the `from` statement(s). I doubt it's an issue with the library, because [here's a demo](https://emiliorizzo.github.io/vue-d3-network/) where there's a lot more nodes and edges with little to no lag. 

I've removed courses in the `from (....)` for now, and I think showing multiple graphs will be a better approach since the `from (....)` introduces multiple ways to fulfill the prerequisites for a course.

EDIT: By removing courses in the `from` statement from the graph, there's little to no lag.
